#!/bin/bash
# 手动安装ChromeDriver脚本
# 请按照以下步骤操作：

echo "=== ChromeDriver安装指南 ==="
echo ""
echo "由于网络限制，需要手动安装ChromeDriver。请按以下步骤操作："
echo ""
echo "步骤1: 打开终端，运行以下命令安装Homebrew（如果未安装）："
echo '  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"'
echo ""
echo "步骤2: 安装ChromeDriver："
echo "  brew install --cask chromedriver"
echo ""
echo "步骤3: 验证安装："
echo "  chromedriver --version"
echo ""
echo "步骤4: 运行监控系统："
echo "  cd /Users/z11/Desktop/ai_manager/机票价格监控"
echo "  python3 start_monitor.py"
echo ""
echo "=== 或者使用以下替代方案 ==="
echo ""
echo "方案A: 手动下载ChromeDriver"
echo "  1. 访问 https://chromedriver.chromium.org/downloads"
echo "  2. 下载与Chrome版本匹配的ChromeDriver"
echo "  3. 解压并将chromedriver移动到 /usr/local/bin/"
echo ""
echo "方案B: 使用Safari（需要启用远程自动化）"
echo "  1. 打开Safari → 偏好设置 → 高级"
echo "  2. 勾选'在菜单栏中显示开发菜单'"
echo "  3. 开发 → 允许远程自动化"
echo ""
echo "方案C: 使用其他机票网站（如去哪儿、飞猪）"
echo ""